apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-deployment
  labels:
    app: k8s
  namespace: production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8s
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
  template:
    metadata:
      labels:
        app: k8s
    spec:
      containers:
      - name: k8s
        image: ozgurozturknet/k8s:v1
        ports:
        - containerPort: 80
